//
// Created by ivanprjcts on 2/05/15.
//

#ifndef RAINBOWTABLESCRACK_CHARSET_H
#define RAINBOWTABLESCRACK_CHARSET_H

#endif //RAINBOWTABLESCRACK_CHARSET_H




#define NUMERIC 1
#define LOWERALPHA 2
#define UPPERALPHA 4
#define SPECIALCHARS 8